### ISSUE TITLE
Linker fails for Estimote SDK when using Xcode 5

### ISSUE THREAD

**Issue by VicenteFava** [Estimote/iOS-SDK#153]
I installed the Estimote SDK following the manual installation and when I try to run the project in a device I have the following error:

ld: framework not found Metal for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I followed the three steps that are mentioned in the installation. 

I'm using XCODE 5.1 and the iOs verison of the device is 7.1.2.

Thanks

**Comment by heypiotr** [comment]
What are the reasons you wouldn't want to switch to Xcode 6? Doing some workarounds in the build process just to make the SDK work with the previous generation IDE looks a little suboptimal. Let us know if you have some strong opinions here.

**Comment by EddyVerbruggen** [comment]
@heypiotr I had that requirement last year, but it's no longer required for our build environment. Thanks!

**Comment by burczyk** [comment]
Hi. I had the same problem lately with one of my customers. 
It turns out the Xcode 6.x adds Metal (and probably other) framework as a dependency to static library.
`otool -arch all -fl libEstimoteSDK.a | grep Metal` returns 114 'Metal' entries.
@heypiotr in my case that was the solution:

1. I set `Build Active Architectures Only` to `NO` in both `debug` and `release` configurations.
2. I double checked `Valid Architectures` and `Architectures` - I was missing `armv7s` support. In your case it's probably not a problem but you can always run: `lipo -info libEstimoteSDK.a` to check if all architectures are supported. Current results:
`Architectures in the fat file: libEstimoteSDK.a are: armv7 armv7s i386 x86_64 arm64`
3. I changed `iOS Deployment Target` to iOS 6 → this is probably **the most important thing**.

When I compiled and checked my library with otool after these steps 'Metal' framework was no longer present and client was able to build his app.

There is one more option `Link frameworks Automatically` but it has probably only impact on final app, not the library itself. But if points 1-3 fail you can check it too.

Btw, in my case this situation occurred on Xcode 6, my customer only had an old application that started in Xcode 5 but now develops it in Xcode 6. So it's probably not only Xcode 5 issue but rather a legacy configuration.
