### ISSUE TITLE
iPhone 5C iOS 8.1 issue

### ISSUE THREAD

**Issue by onskulis** [Estimote/iOS-SDK#162]
Hello,

I just updated estimote SDK from 1.3.0 to 2.2.1 to be able to communicate with beacons in iOS 8. Followed your articles to set up location update and I noticed funny behavior.

I can monitore in background/foregroud, but when I range I always get empty list of beacons. My UUID is of course changed, not the original estimote UUID. Why is that?

**Comment by heypiotr** [comment]
There was a bug in how the `region` parameter was being passed into the `didEnterRegion` delegate. Since you were using that "buggy" region to start ranging, this could've been the reason why ranging was returning an empty list of beacons. This has since been fixed—try the newest version of the SDK.
