### ISSUE TITLE
Nearable zone is occationally zero even when in range

### ISSUE THREAD

**Issue by mikaelkindborg** [Estimote/iOS-SDK#179]
**Problem/Question**

The Nearable zone property is sometimes 0 when ranging or monitoring a trigger. 

This has been observed when the nearable is very close and zone is 1 (ESTNearableZoneImmediate). Happens quite frequently during ranging and monitoring.

Is this a bug or something the application should compensate for (e.g. by ignoring zone zero values or sampling/filtering values over time)?

What does ESTNearableZoneUnknown mean really? The documentation does not say much.

When the nearable goes out of range it is reported with zone zero for a period, it would be convenient to be able to rely on this.

**Comment by martinklimek** [comment]
@divineprog, ESTNearableZoneUnknown is expected value and it happens when beacon was not found in particular time window. Currently stickers are advertising with time interval 2,5 sec, and sometimes bluetooth packet can be lost. So taking that into count it is possible to get Unknown state from time to time. I will try verify if there is no bug there anyway. Thanks for feedback.

**Comment by divineprog** [comment]
Thanks a lot for the update and the clarification! It makes sense that you get unknown zone/proximity now and then, apps will have to take that into account, and it would also be possible to wrap this in a library if one would want to filter out unknown values in some way. Thanks again :)

**Comment by MatthewAnthonyBordas** [comment]
This issue should be closed out then :)

**Comment by heypiotr** [comment]
Good call! Bumping Tx power & reducing the adv interval of stickers should help BTW, same as beacons and `CLProximityUnkown`.
