### ISSUE TITLE
duplicate symbol _sbox issue, one project with EstimoteSDK + SensoroSDK for arm64

### ISSUE THREAD

**Issue by ErmaCKoK** [Estimote/iOS-SDK#216]
I have some issue:
EstimoteSDK v4.0.0-beta8
SensoroSDK v4.1.3

when import two SDK  Estimate + Sensoro for one project I have this issue:
duplicate symbol _sbox in:
    Dependencies/estimote-sdk/EstimoteSDK.framework/EstimoteSDK(Encryption.o)
    /Users/ErmaCK/Documents/PointInside/ios-beacontool/Dependencies/SensoroBeaconKit/libSensoroBeaconKit.a(SBK_TI_aes_128.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This issue only for arm64. Can you help me?
Thanks

**Comment by heypiotr** [comment]
Thanks, we're looking into that. I think Sensoro uses the same Nordic BLE chip that we do, so this is likely just a conflict due to a duplicated Nordic library we both use in our own SDKs. We've seen something similar before with Estimote + Kontakt SDKs in a single project. We'll see if we can namespace that.

**Comment by heypiotr** [comment]
Fixed in beta13. Also, let's move beta SDK bug reports into the beta SDK repo. If you need access, shoot me an email: piotr@estimote.com
